#!/bin/bash
t=0
t1=0
t2=0
rm dados_t1.csv
rm saidas_t1.csv
for j in {1..300}
do
	for i in {1..10}
	do
		printf "iteracao $i do teste $j\n"
		t1="$(date +%s%N)"
		./tp3 tarefa1 testes_t1/"teste t1 $i para n=50*$j.txt" >> saidas_t1.csv
		t2="$(date +%s%N)"
		printf "," >> saidas_t1.csv
		t=$((t2 - t1))
		printf "$t," >> dados_t1.csv
	done
	printf "\n" >> saidas_t1.csv
	printf "\n" >> dados_t1.csv
done
