#!/bin/bash
t=0
t1=0
t2=0
rm dados_t2.csv
for j in {1..150}
do
	for i in {1..10}
	do
		printf "iteracao $i do teste $j\n"
		t1="$(date +%s%N)"
		./tp3 tarefa2 testes_t2/"teste t2 $i para n=20*$j m=40*$j.txt" > /dev/null
		t2="$(date +%s%N)"
		t=$((t2 - t1))
		printf "$t," >> dados_t2.csv
	done
	printf "\n" >> dados_t2.csv
done
